### ISSUE TITLE
Austausch

### ISSUE THREAD

**Issue by crelder** [sthesing/Zettels#10]
Hallo Stefan,

ich bin eben auf Dein Zettelkastenprogramm aufmerksam geworden. Mich würde interessiere, wie Deine Erfahrungen bei der Nutzung Deines Zettelkastens sind. 
Hättest Du Interesse Dich mal auszutauschen?

Grüße aus Karlsruhe

Christian

**Comment by sthesing** [comment]
Sorry, jetzt erst gesehen. Na klar habe ich Interesse.

**Comment by crelder** [comment]
Super, freut mich. Willst Du mir auf _masked_ schreiben? Dann können wir dort das Gespräch weiterführen? 
(Will meine Nummer nicht öffentlich auf Github machen).

Grüße nach Hamburg

Christian
