### ISSUE TITLE
zettel --setup fails with an error

### ISSUE THREAD

**Issue by bakirillov** [sthesing/Zettels#11]
Hello.

I have installed zettels with pip on ubuntu 20.04, Python 3.7.5.
The setup fails with the following error:

`zettels --setup
Traceback (most recent call last):
  File "/-------/bin/zettels", line 5, in <module>
    from zettels.zettels import main
  File "-----/lib/python3.7/site-packages/zettels/zettels.py", line 34, in <module>
    import xdg.BaseDirectory
ModuleNotFoundError: No module named 'xdg.BaseDirectory'`

xdg 4.0.1 is installed
What should I do?

**Comment by sthesing** [comment]
You probably need the python bindings for xdg. Should be `python-xdg` or `python3-xdg` or something similar.

By the way, I reimplemented zettels in rust and released it just today, maybe you want to have a look at it, if you're just getting started: https://gitlab.com/sthesing/zettels

**Comment by bakirillov** [comment]
Thanks. I'm actually almost finished with my own implementation, but I'll take a look at the rust version;)

**Comment by sthesing** [comment]
You do that. It has deb-packages now, so it should be easy to give it a try.

Closing this issue now. Feel free to open new ones if you have more questions.
