### ISSUE TITLE
add more migration information

### ISSUE THREAD

**Issue by epogrebnyak** [sthesing/Zettels#12]
I think zettels is an important project, useful for many python users. Perhaps a bit more detail for novice users like myself can be useful:

After migration to rust will `pip install zettels` still work (via Rust executable API?) and can be updated or it is stuck as of current python implementation?

Also wonder how you get about separating notes management and html site rendering, not quite clear.

**Comment by sthesing** [comment]
Thanks for the suggestion. I must admit, I wasn't aware that anyone but myself is actually using this :-)

I will update the README.md. But as a quick answer for you: 
Yes, users of the Python implementation are essentially stuck with the current version (except some bugfixes, I guess). I suggest migrating to the Rust reimplementation.

As for your second question: I'm currently working on more howtos and documentation for the rust version, including workflows with pandoc for academic writing, blogging etc. Is that what you're asking for?

Lastly, allow me a question of my own: What Rust executable API are you talking about?

**Comment by epogrebnyak** [comment]
> Lastly, allow me a question of my own: What Rust executable API are you talking about?

I guess there isn't one... I thought maybe https://gitlab.com/sthesing/libzettels was an executable with some bindings that could be used from python, but just a guess. 

Maybe README should be more clear about migration. From unfamilair user viewpoint I was reading:
- ... reimplementation...
- ... libzettels, sporting an API that can be used to easily build other user interfaces ...

It made impression something new was available in Python. This readme also appears in pypi - I think it should have just what is relevant for python usage.

**Comment by sthesing** [comment]
OK, thanks for the quick reply.
It might be implement a python "client" using the libzettels library, but I neither want to implement nor maintain one. So I strongly suggest to migrate to the rust version.
I added some migration info, as you suggested. Thanks again for that. I hope it helps. Closing this issue. Feel free to open new ones if you need help migrating or if you have other questions.

**Comment by epogrebnyak** [comment]
Thanks for updating the information. I do not know Rust, but sure it can be a fast and effcient implementation.
